<a href="https://colab.research.google.com/github/sudama-inc/EDA-with-Pandas-and-Numpy/blob/main/process_huge_datasets_in_pandas_using_chunks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [3]:
df = pd.read_csv('/content/drive/My Drive/Datasets/creditcard.csv')
df.shape

(284807, 31)

In [4]:
chunk_size = 100  # Number of rows per chunk
total_iterations = 5  # Total number of iterations

# Read the dataset in specified number of iterations
for i in range(total_iterations):
    start_row = i * chunk_size
    end_row = start_row + chunk_size

    # Read the chunk for the current iteration
    chunk = pd.read_csv('/content/drive/My Drive/Datasets/creditcard.csv', chunksize=chunk_size)

    # Process the chunk as needed
    display(chunk)  # Example: printing the chunk for demonstration purposes

In [11]:
chunk_size = 100  # Number of rows per chunk
total_entries = 500  # Total number of entries to retrieve
total_iterations = total_entries // chunk_size  # Calculate the total number of iterations based on chunk size

chunks = []  # List to store the chunks

# Read the dataset in the specified number of iterations
for i in range(total_iterations):
    # Calculate the start and end rows for the current iteration
    start_row = i * chunk_size
    end_row = start_row + chunk_size

    # Read the chunk for the current iteration
    chunk = pd.read_csv('/content/drive/My Drive/Datasets/creditcard.csv', skiprows=range(1, start_row), nrows=chunk_size)

    chunks.append(chunk)  # Append the chunk to the list

# Concatenate all the chunks into a single DataFrame
chunk_df = pd.concat(chunks, ignore_index=True)

# Process the concatenated DataFrame as needed
display(chunk_df)  # Example: printing the chunk for demonstration purposes

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,365,-0.456586,0.541708,1.331297,0.559447,0.184045,0.612792,0.632759,0.152253,-0.202196,...,-0.134465,-0.316126,-0.072149,-0.749725,-0.039644,0.472098,0.075612,0.099985,74.22,0
496,365,-1.209437,0.949446,-0.429811,-2.640094,2.601387,3.056966,0.473495,0.280729,0.853043,...,-0.214920,-0.449815,-0.088677,1.030439,-0.048967,0.671979,-0.612153,-0.224000,0.68,0
497,366,-1.185698,-0.386510,1.623072,1.636406,1.102506,-0.683317,-0.303337,0.285653,-0.056085,...,0.068753,-0.006952,0.040889,0.040937,0.009224,-0.201042,0.106580,0.140465,9.99,0
498,366,1.020399,-0.639479,0.941568,0.121307,-0.996320,0.177803,-0.589656,0.153583,0.835979,...,-0.140624,-0.341663,-0.060548,0.116672,0.144624,0.932850,-0.049522,0.018131,97.47,0
499,367,1.256217,0.255028,0.277716,0.706677,-0.495831,-1.106735,-0.008493,-0.124504,0.243687,...,-0.303927,-0.943830,0.146551,0.307164,0.169070,0.099129,-0.032095,0.027743,1.29,0